### ISSUE TITLE
Deployed to wrong URL

### ISSUE THREAD

**Issue by foolip** [Ecosystem-Infra/ecosystem-infra-rotation#53]
https://github.com/Ecosystem-Infra/ecosystem-infra-rotation/runs/865668584?check_suite_focus=true#step:6:13 deployed to https://ecosystem-infra-rotation.uk.r.appspot.com and that seems to have been the case for deploys two months ago as well.

Links are to https://ecosystem-infra-rotation.appspot.com/ which is still up, so something needs to change.

**Comment by stephenmcgruer** [comment]
They're the same thing for grandfathered apps, as far as I know :). I expect they couldn't not support old URLs, because it would break... like every appengine app.

https://cloud.google.com/appengine/docs/standard/python/how-requests-are-routed#region-id

**Comment by foolip** [comment]
Reopening to update URLs.
